---
- include: docker.yml
- include: kvm.yml

- name: Install nodejs + yarn
  pacman:
    name:
      - nodejs
      - yarn
      - npm
    state: present

- name: Install pip
  pacman:
    name:
      - python-pip 
    state: present

- name: Install terraform lsp
  aur:
    name:
      - terraform-lsp
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install python linters + helpers
  pip:
    name:
      - isort
      - autopep8
      - flake8
      - poetry

- name: Install neovim-remote for vimtex
  pip:
    name:
      -  neovim-remote

- name: install nodejs neovim provider
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - neovim

- name: install javascript linters + helpers
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - eslint
    - tslint
    - prettier
