---
- name: Install YubiKey Manager + Yubikey PAM module
  pacman:
    name:
      - yubikey-manager-qt
      - yubico-pam
    state: present


- name: Install libu2f-host for browser u2f
  pacman:
    name:
      - libu2f-host

- name: Install smartcard libs/tools
  pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid
    state: present

- name: Allow passwordless sudo if Yubikey is inserted
  lineinfile:
    path: /etc/pam.d/sudo
    line: "auth            sufficient      pam_yubico.so id=55114"
    insertbefore: BOF
  become: yes


- name: Allow passwordless login if Yubikey is inserted
  lineinfile:
    path: /etc/pam.d/login
    line: "auth            sufficient      pam_yubico.so id=55114"
    insertbefore: BOF
  become: yes
