---
# - name: Create user group
#   group:
#     name: "{{ user.group }}"
#     state: present
#   tags:
#     - user
#
# - name: Create user and assign to group
#   user:
#     name: "{{ user.name }}"
#     group: "{{ user.group }}"
#     password: "{{ user_password|password_hash('sha512') }}"
#     shell: "{{ user.shell }}"
#     update_password: on_create
#     uid: "{{ user.uid }}"
#     groups: uucp
#     append: yes
#   tags:
#     - user
#
- name: Add user to 'video' group
  user:
    append: yes
    name: "{{ user.name }}"
    groups:
      - "video"
  tags:
    - user

- name: Create user log dir
  file:
    path: /home/{{ user.name }}/{{ user.log.dir }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: user.log.dir is defined
  tags:
    - user

- name: Install logrotate
  pacman:
      name: logrotate
      state: present

- name: Push logrotate config for user logs
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/user
  when: user.log.dir is defined
  tags:
    - user

- name: Create user socket directory
  file:
    path: /run/user/{{ user.uid }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
  tags:
    - user

- name: Start user systemd instance
  service:
    name: "user@{{ user.uid }}"
    state: started
  notify: stop systemd per-user instance
  tags:
    - user

- name: "Create getty@tty1 override"
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory
    mode: 0755
  become: true
  tags:
    - user

- name: "Set {{ user.name }} as default tty1 username"
  template:
    src: override.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    mode: 0644
  become: true
  tags:
    - user
